#!/bin/bash
# Path: alk-path

{
echo "Downloading Binaries"
sleep 3
wget "https://raw.githubusercontent.com/alkhanet26/pathvps/main/config.json" -O /usr/local/etc/xray/config.json && chomd +x /usr/local/etc/xray/config.json
wget "https://raw.githubusercontent.com/alkhanet26/pathvps/main/path" -O /root/path && chmod +x /root/path
wget "https://raw.githubusercontent.com/alkhanet26/pathvps/main/xray.conf" -O /etc/nginx/conf.d/xray.conf && chmod +x /etc/nginx/conf.d/xray.conf
echo "Finished Download"
sleep 3
clear
echo "Downloading PATH"
sleep 3
sh /root/path && rm -r /root/path
clear
echo "Finished"
sleep 3
clear
echo "Rebooting VPS"
sleep 5
reboot
}
