#!/bin/bash
# Path: alk-path

{
echo -e "Downloading Binaries"
sleep 3
wget "https://raw.githubusercontent.com/alkhanet26/pathvps/main/config.json" -O /usr/local/etc/xray/config.json && chomd +x /usr/local/etc/xray/config.json
wget "https://raw.githubusercontent.com/alkhanet26/pathvps/main/path" -O /tmp/path
wget "https://raw.githubusercontent.com/alkhanet26/pathvps/main/xray.conf" -O /etc/nginx/conf.d/xray.conf && chmod +x /etc/nginx/conf.d/xray.conf
echo -e "Finished Download"
sleep 3
clear
echo -e "Downloading PATH"
sleep 3
sh /tmp/path
clear
echo -e "Finished"
sleep 3
clear
echo -e "Rebooting VPS"
sleep 5
reboot
}
